name: ⚛️ Deploy React Stock Master to VPS (Nginx)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Create env for build
        run: |
          printf "%s" "${{ secrets.REACT_ENV }}" > .env

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "dist"
          target: "/tmp/react_build"

      - name: Activate build on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            set -e

            sudo mkdir -p /var/www/stock-master
            sudo rm -rf /var/www/stock-master/*
            sudo cp -r /tmp/react_build/dist/* /var/www/stock-master/

            sudo chown -R www-data:www-data /var/www/stock-master

            sudo nginx -t
            sudo systemctl reload nginx